import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Linktree | auth ",
    description: "Generated by create next app",
  };

export default function Authlayout( {children}: {children: React.ReactNode}) {
  return (
    <div className="grid grid-cols-1 h-screen">
        <div className="flex flex-col items-center justify-center">
            {children}
        </div>
    </div>
  )
}
